// darwin_abi_gen header|ctype — prints the Darwin arm64 numbers and layouts the Android
// libSystem layer translates from (docs/LAUNCHER.md, Stage 3). Compiled on the Mac against the
// macOS SDK: iOS and macOS arm64 share these (same libc, same kernel ABI). The output is
// committed (android/launcher/darwin/) and checked by tools/tests/darwin_abi_test.sh.
//   header: namespace darwin { constexpr long kNAME = value; ... } plus X-macro lists of the
//           names bionic also defines (errno, signals, socket options), for translation tables.
//   ctype:  the C locale's _RuneLocale tables (__runetype, __maplower, __mapupper).
#include <_ctype.h>
#include <CommonCrypto/CommonDigest.h>
#include <CommonCrypto/CommonHMAC.h>
#include <arpa/inet.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <ifaddrs.h>
#include <locale.h>
#include <limits.h>
#include <mach/mach.h>
#include <mach/mach_time.h>
#include <net/if.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <poll.h>
#include <pthread.h>
#include <runetype.h>
#include <sched.h>
#include <signal.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/un.h>
#include <sys/utsname.h>
#include <time.h>
#include <unistd.h>
#include <wchar.h>
#include <xlocale.h>

#define C(name) printf("constexpr long k%s = %lldL;\n", #name, (long long)(name))
#define CX(name) printf("constexpr long k%s = 0x%llXL;\n", #name, (long long)(name))
#define SZ(tag, type) printf("constexpr long kSizeof_%s = %zuL;\n", tag, sizeof(type))
#define FIELD(tag, type, f)                                                                          \
  printf("constexpr long kOffsetof_%s_%s = %zuL;\nconstexpr long kSizeof_%s_%s = %zuL;\n", tag, #f, \
         offsetof(type, f), tag, #f, sizeof(((type *)0)->f))
#define X(name) printf(" X(%s, %lld)", #name, (long long)(name))

static void header(void) {
  printf("// Generated by tools/android/darwin_abi_gen.c from the macOS SDK. Do not edit:\n"
         "// make darwin-abi. Darwin arm64 numbers and layouts (iOS uses the same).\n"
         "#pragma once\n\nnamespace darwin {\n\n");
  // errno (bionic shares every name in MCFM_DARWIN_ERRNOS; the values differ).
  C(EPERM); C(ENOENT); C(EINTR); C(EIO); C(EBADF); C(EAGAIN); C(EWOULDBLOCK); C(ENOMEM); C(EACCES);
  C(EEXIST); C(ENOTDIR); C(EISDIR); C(EINVAL); C(ENOSPC); C(EPIPE); C(ERANGE); C(EDEADLK);
  C(ENOSYS); C(ENOTSUP); C(EOPNOTSUPP); C(EINPROGRESS); C(EALREADY); C(ENOPROTOOPT); C(EAFNOSUPPORT);
  C(EADDRINUSE); C(ECONNRESET); C(ENOTCONN); C(ETIMEDOUT); C(ECONNREFUSED); C(ENOTTY);
  C(EBUSY); C(ENOTEMPTY); C(ENAMETOOLONG); C(EFAULT); C(ESRCH); C(EILSEQ); C(EOVERFLOW);
  // fcntl.h, unistd.h
  C(O_RDONLY); C(O_WRONLY); C(O_RDWR); C(O_ACCMODE); CX(O_NONBLOCK); CX(O_APPEND); CX(O_CREAT);
  CX(O_TRUNC); CX(O_EXCL); CX(O_NOFOLLOW); CX(O_CLOEXEC); CX(O_DIRECTORY); CX(O_SYNC); CX(O_NOCTTY);
  CX(O_DSYNC);
  C(F_DUPFD); C(F_GETFD); C(F_SETFD); C(F_GETFL); C(F_SETFL); C(F_GETLK); C(F_SETLK); C(F_SETLKW);
  C(F_DUPFD_CLOEXEC); C(F_NOCACHE); C(F_FULLFSYNC); C(FD_CLOEXEC); C(F_RDLCK); C(F_WRLCK); C(F_UNLCK);
  C(SEEK_SET); C(SEEK_CUR); C(SEEK_END); C(F_OK); C(R_OK); C(W_OK); C(X_OK);
  CX(S_IFMT); CX(S_IFDIR); CX(S_IFREG); CX(S_IFLNK); CX(S_IFCHR); CX(S_IFBLK); CX(S_IFIFO); CX(S_IFSOCK);
  C(DT_UNKNOWN); C(DT_DIR); C(DT_REG); C(DT_LNK);
  // sys/mman.h
  C(PROT_NONE); C(PROT_READ); C(PROT_WRITE); C(PROT_EXEC); CX(MAP_SHARED); CX(MAP_PRIVATE);
  CX(MAP_FIXED); CX(MAP_ANON); C(MS_ASYNC); C(MS_SYNC); C(MS_INVALIDATE);
  // unistd.h sysconf
  C(_SC_ARG_MAX); C(_SC_CLK_TCK); C(_SC_OPEN_MAX); C(_SC_PAGESIZE); C(_SC_PAGE_SIZE);
  C(_SC_NPROCESSORS_CONF); C(_SC_NPROCESSORS_ONLN); C(_SC_PHYS_PAGES);
  // sockets
  C(AF_UNSPEC); C(AF_UNIX); C(AF_INET); C(AF_INET6); C(SOCK_STREAM); C(SOCK_DGRAM); C(SOCK_RAW);
  C(SOCK_SEQPACKET); CX(SOL_SOCKET); CX(SO_NOSIGPIPE); C(IPPROTO_IP); C(IPPROTO_IPV6);
  C(IPPROTO_TCP); C(IPPROTO_UDP); C(TCP_NODELAY); C(TCP_KEEPALIVE); CX(MSG_NOSIGNAL);
  C(SHUT_RD); C(SHUT_WR); C(SHUT_RDWR); C(SCM_RIGHTS); C(SOMAXCONN);
  CX(AI_PASSIVE); CX(AI_CANONNAME); CX(AI_NUMERICHOST); CX(AI_NUMERICSERV); CX(AI_ADDRCONFIG);
  CX(AI_V4MAPPED); CX(AI_ALL); CX(NI_NOFQDN); CX(NI_NUMERICHOST); CX(NI_NAMEREQD);
  CX(NI_NUMERICSERV); CX(NI_DGRAM);
  CX(FIONBIO); CX(FIONREAD); CX(POLLIN); CX(POLLPRI); CX(POLLOUT); CX(POLLERR); CX(POLLHUP);
  CX(POLLNVAL); C(FD_SETSIZE);
  CX(IFF_UP); CX(IFF_BROADCAST); CX(IFF_LOOPBACK); CX(IFF_POINTOPOINT); CX(IFF_RUNNING);
  CX(IFF_MULTICAST);
  // signals
  C(SIG_BLOCK); C(SIG_UNBLOCK); C(SIG_SETMASK); CX(SA_ONSTACK); CX(SA_RESTART); CX(SA_RESETHAND);
  CX(SA_NOCLDSTOP); CX(SA_NODEFER); CX(SA_NOCLDWAIT); CX(SA_SIGINFO); C(NSIG);
  // locale
  C(LC_ALL); C(LC_COLLATE); C(LC_CTYPE); C(LC_MONETARY); C(LC_NUMERIC); C(LC_TIME); C(LC_MESSAGES);
  CX(LC_COLLATE_MASK); CX(LC_CTYPE_MASK); CX(LC_MONETARY_MASK); CX(LC_NUMERIC_MASK);
  CX(LC_TIME_MASK); CX(LC_MESSAGES_MASK); CX(LC_ALL_MASK);
  // ctype (runetype.h)
  CX(_CTYPE_A); CX(_CTYPE_C); CX(_CTYPE_D); CX(_CTYPE_G); CX(_CTYPE_L); CX(_CTYPE_P); CX(_CTYPE_S);
  CX(_CTYPE_U); CX(_CTYPE_X); CX(_CTYPE_B); CX(_CTYPE_R); CX(_CTYPE_I); CX(_CTYPE_T); CX(_CTYPE_Q);
  CX(_CTYPE_SW0); CX(_CTYPE_SW1); CX(_CTYPE_SW2); CX(_CTYPE_SW3); CX(_CTYPE_SWM); C(_CTYPE_SWS);
  C(_CACHED_RUNES);
  // pthread
  C(PTHREAD_CREATE_JOINABLE); C(PTHREAD_CREATE_DETACHED); C(PTHREAD_MUTEX_NORMAL);
  C(PTHREAD_MUTEX_ERRORCHECK); C(PTHREAD_MUTEX_RECURSIVE); C(PTHREAD_MUTEX_DEFAULT);
  C(PTHREAD_PROCESS_PRIVATE); C(PTHREAD_PROCESS_SHARED); C(PTHREAD_INHERIT_SCHED);
  C(PTHREAD_EXPLICIT_SCHED); C(PTHREAD_SCOPE_SYSTEM); C(SCHED_OTHER); C(SCHED_FIFO); C(SCHED_RR);
  C(PTHREAD_STACK_MIN); C(PTHREAD_KEYS_MAX);
  CX(_PTHREAD_MUTEX_SIG_init); CX(_PTHREAD_ERRORCHECK_MUTEX_SIG_init);
  CX(_PTHREAD_RECURSIVE_MUTEX_SIG_init); CX(_PTHREAD_FIRSTFIT_MUTEX_SIG_init);
  CX(_PTHREAD_COND_SIG_init); CX(_PTHREAD_ONCE_SIG_init); CX(_PTHREAD_RWLOCK_SIG_init);
  // mach, time
  C(KERN_SUCCESS); C(KERN_INVALID_ARGUMENT); C(HOST_VM_INFO); C(HOST_VM_INFO_COUNT);
  C(SYNC_POLICY_FIFO); C(KERN_OPERATION_TIMED_OUT); C(CLOCKS_PER_SEC);
  // CommonCrypto
  C(kCCHmacAlgSHA1); C(kCCHmacAlgSHA256); C(CC_SHA256_DIGEST_LENGTH);
  printf("\n");

  SZ("stat", struct stat);
  FIELD("stat", struct stat, st_dev); FIELD("stat", struct stat, st_mode);
  FIELD("stat", struct stat, st_nlink); FIELD("stat", struct stat, st_ino);
  FIELD("stat", struct stat, st_uid); FIELD("stat", struct stat, st_gid);
  FIELD("stat", struct stat, st_rdev); FIELD("stat", struct stat, st_atimespec);
  FIELD("stat", struct stat, st_mtimespec); FIELD("stat", struct stat, st_ctimespec);
  FIELD("stat", struct stat, st_birthtimespec); FIELD("stat", struct stat, st_size);
  FIELD("stat", struct stat, st_blocks); FIELD("stat", struct stat, st_blksize);
  FIELD("stat", struct stat, st_flags); FIELD("stat", struct stat, st_gen);
  SZ("dirent", struct dirent);
  FIELD("dirent", struct dirent, d_ino); FIELD("dirent", struct dirent, d_seekoff);
  FIELD("dirent", struct dirent, d_reclen); FIELD("dirent", struct dirent, d_namlen);
  FIELD("dirent", struct dirent, d_type); FIELD("dirent", struct dirent, d_name);
  SZ("sockaddr", struct sockaddr);
  FIELD("sockaddr", struct sockaddr, sa_len); FIELD("sockaddr", struct sockaddr, sa_family);
  FIELD("sockaddr", struct sockaddr, sa_data);
  SZ("sockaddr_in", struct sockaddr_in);
  FIELD("sockaddr_in", struct sockaddr_in, sin_port); FIELD("sockaddr_in", struct sockaddr_in, sin_addr);
  SZ("sockaddr_in6", struct sockaddr_in6);
  FIELD("sockaddr_in6", struct sockaddr_in6, sin6_port);
  FIELD("sockaddr_in6", struct sockaddr_in6, sin6_flowinfo);
  FIELD("sockaddr_in6", struct sockaddr_in6, sin6_addr);
  FIELD("sockaddr_in6", struct sockaddr_in6, sin6_scope_id);
  SZ("sockaddr_un", struct sockaddr_un); FIELD("sockaddr_un", struct sockaddr_un, sun_path);
  SZ("sockaddr_storage", struct sockaddr_storage);
  SZ("addrinfo", struct addrinfo);
  FIELD("addrinfo", struct addrinfo, ai_flags); FIELD("addrinfo", struct addrinfo, ai_family);
  FIELD("addrinfo", struct addrinfo, ai_socktype); FIELD("addrinfo", struct addrinfo, ai_protocol);
  FIELD("addrinfo", struct addrinfo, ai_addrlen); FIELD("addrinfo", struct addrinfo, ai_canonname);
  FIELD("addrinfo", struct addrinfo, ai_addr); FIELD("addrinfo", struct addrinfo, ai_next);
  SZ("hostent", struct hostent);
  FIELD("hostent", struct hostent, h_name); FIELD("hostent", struct hostent, h_aliases);
  FIELD("hostent", struct hostent, h_addrtype); FIELD("hostent", struct hostent, h_length);
  FIELD("hostent", struct hostent, h_addr_list);
  SZ("ifaddrs", struct ifaddrs);
  FIELD("ifaddrs", struct ifaddrs, ifa_next); FIELD("ifaddrs", struct ifaddrs, ifa_name);
  FIELD("ifaddrs", struct ifaddrs, ifa_flags); FIELD("ifaddrs", struct ifaddrs, ifa_addr);
  FIELD("ifaddrs", struct ifaddrs, ifa_netmask); FIELD("ifaddrs", struct ifaddrs, ifa_dstaddr);
  FIELD("ifaddrs", struct ifaddrs, ifa_data);
  SZ("msghdr", struct msghdr);
  FIELD("msghdr", struct msghdr, msg_name); FIELD("msghdr", struct msghdr, msg_namelen);
  FIELD("msghdr", struct msghdr, msg_iov); FIELD("msghdr", struct msghdr, msg_iovlen);
  FIELD("msghdr", struct msghdr, msg_control); FIELD("msghdr", struct msghdr, msg_controllen);
  FIELD("msghdr", struct msghdr, msg_flags);
  SZ("cmsghdr", struct cmsghdr);
  SZ("linger", struct linger); SZ("ip_mreq", struct ip_mreq); SZ("ipv6_mreq", struct ipv6_mreq);
  SZ("pollfd", struct pollfd); SZ("fd_set", fd_set);
  SZ("flock", struct flock);
  FIELD("flock", struct flock, l_start); FIELD("flock", struct flock, l_len);
  FIELD("flock", struct flock, l_pid); FIELD("flock", struct flock, l_type);
  FIELD("flock", struct flock, l_whence);
  SZ("sigaction", struct sigaction);
  FIELD("sigaction", struct sigaction, __sigaction_u); FIELD("sigaction", struct sigaction, sa_mask);
  FIELD("sigaction", struct sigaction, sa_flags);
  SZ("sigset_t", sigset_t);
  SZ("utsname", struct utsname);
  FIELD("utsname", struct utsname, sysname); FIELD("utsname", struct utsname, nodename);
  FIELD("utsname", struct utsname, release); FIELD("utsname", struct utsname, version);
  FIELD("utsname", struct utsname, machine);
  SZ("tm", struct tm); FIELD("tm", struct tm, tm_gmtoff); FIELD("tm", struct tm, tm_zone);
  SZ("timeval", struct timeval); FIELD("timeval", struct timeval, tv_usec);
  SZ("timespec", struct timespec);
  SZ("pthread_t", pthread_t); SZ("pthread_attr_t", pthread_attr_t);
  SZ("pthread_mutex_t", pthread_mutex_t); SZ("pthread_mutexattr_t", pthread_mutexattr_t);
  SZ("pthread_cond_t", pthread_cond_t); SZ("pthread_condattr_t", pthread_condattr_t);
  SZ("pthread_once_t", pthread_once_t); SZ("pthread_key_t", pthread_key_t);
  SZ("pthread_rwlock_t", pthread_rwlock_t); SZ("sched_param", struct sched_param);
  SZ("mbstate_t", mbstate_t);
  SZ("RuneLocale", _RuneLocale);
  FIELD("RuneLocale", _RuneLocale, __magic); FIELD("RuneLocale", _RuneLocale, __encoding);
  FIELD("RuneLocale", _RuneLocale, __invalid_rune); FIELD("RuneLocale", _RuneLocale, __runetype);
  FIELD("RuneLocale", _RuneLocale, __maplower); FIELD("RuneLocale", _RuneLocale, __mapupper);
  SZ("vm_statistics", vm_statistics_data_t);
  FIELD("vm_statistics", vm_statistics_data_t, free_count);
  FIELD("vm_statistics", vm_statistics_data_t, active_count);
  FIELD("vm_statistics", vm_statistics_data_t, inactive_count);
  FIELD("vm_statistics", vm_statistics_data_t, wire_count);
  SZ("mach_timebase_info", mach_timebase_info_data_t);
  SZ("CC_SHA256_CTX", CC_SHA256_CTX); SZ("CCHmacContext", CCHmacContext);
  printf("\n}  // namespace darwin\n\n");

  // Names bionic defines too: translation tables are X(name, darwin value) lists.
  printf("// X(name, Darwin value): every name here exists in bionic too.\n");
  printf("#define MCFM_DARWIN_ERRNOS(X)");
  X(EPERM); X(ENOENT); X(ESRCH); X(EINTR); X(EIO); X(ENXIO); X(E2BIG); X(ENOEXEC); X(EBADF);
  X(ECHILD); X(EDEADLK); X(ENOMEM); X(EACCES); X(EFAULT); X(ENOTBLK); X(EBUSY); X(EEXIST); X(EXDEV);
  X(ENODEV); X(ENOTDIR); X(EISDIR); X(EINVAL); X(ENFILE); X(EMFILE); X(ENOTTY); X(ETXTBSY); X(EFBIG);
  X(ENOSPC); X(ESPIPE); X(EROFS); X(EMLINK); X(EPIPE); X(EDOM); X(ERANGE); X(EAGAIN);
  X(EINPROGRESS); X(EALREADY); X(ENOTSOCK); X(EDESTADDRREQ); X(EMSGSIZE); X(EPROTOTYPE);
  X(ENOPROTOOPT); X(EPROTONOSUPPORT); X(ESOCKTNOSUPPORT); X(EOPNOTSUPP); X(EPFNOSUPPORT);
  X(EAFNOSUPPORT); X(EADDRINUSE); X(EADDRNOTAVAIL); X(ENETDOWN); X(ENETUNREACH); X(ENETRESET);
  X(ECONNABORTED); X(ECONNRESET); X(ENOBUFS); X(EISCONN); X(ENOTCONN); X(ESHUTDOWN);
  X(ETOOMANYREFS); X(ETIMEDOUT); X(ECONNREFUSED); X(ELOOP); X(ENAMETOOLONG); X(EHOSTDOWN);
  X(EHOSTUNREACH); X(ENOTEMPTY); X(EUSERS); X(EDQUOT); X(ESTALE); X(EREMOTE); X(ENOLCK);
  X(ENOSYS); X(EOVERFLOW); X(ECANCELED); X(EIDRM); X(ENOMSG); X(EILSEQ); X(EBADMSG); X(EMULTIHOP);
  X(ENODATA); X(ENOLINK); X(ENOSR); X(ENOSTR); X(EPROTO); X(ETIME); X(EOWNERDEAD);
  X(ENOTRECOVERABLE);
  printf("\n#define MCFM_DARWIN_SIGNALS(X)");
  X(SIGHUP); X(SIGINT); X(SIGQUIT); X(SIGILL); X(SIGTRAP); X(SIGABRT); X(SIGBUS); X(SIGFPE);
  X(SIGKILL); X(SIGUSR1); X(SIGSEGV); X(SIGUSR2); X(SIGPIPE); X(SIGALRM); X(SIGTERM); X(SIGCHLD);
  X(SIGCONT); X(SIGSTOP); X(SIGTSTP); X(SIGTTIN); X(SIGTTOU); X(SIGURG); X(SIGXCPU); X(SIGXFSZ);
  X(SIGVTALRM); X(SIGPROF); X(SIGWINCH); X(SIGIO); X(SIGSYS);
  printf("\n#define MCFM_DARWIN_SOL_SOCKET_OPTIONS(X)");
  X(SO_DEBUG); X(SO_ACCEPTCONN); X(SO_REUSEADDR); X(SO_KEEPALIVE); X(SO_DONTROUTE); X(SO_BROADCAST);
  X(SO_LINGER); X(SO_OOBINLINE); X(SO_REUSEPORT); X(SO_SNDBUF); X(SO_RCVBUF); X(SO_SNDLOWAT);
  X(SO_RCVLOWAT); X(SO_SNDTIMEO); X(SO_RCVTIMEO); X(SO_ERROR); X(SO_TYPE);
  printf("\n#define MCFM_DARWIN_IP_OPTIONS(X)");
  X(IP_TOS); X(IP_TTL); X(IP_HDRINCL); X(IP_MULTICAST_IF); X(IP_MULTICAST_TTL); X(IP_MULTICAST_LOOP);
  X(IP_ADD_MEMBERSHIP); X(IP_DROP_MEMBERSHIP);
  printf("\n#define MCFM_DARWIN_IPV6_OPTIONS(X)");
  X(IPV6_UNICAST_HOPS); X(IPV6_MULTICAST_IF); X(IPV6_MULTICAST_HOPS); X(IPV6_MULTICAST_LOOP);
  X(IPV6_JOIN_GROUP); X(IPV6_LEAVE_GROUP); X(IPV6_V6ONLY);
  printf("\n#define MCFM_DARWIN_MSG_FLAGS(X)");
  X(MSG_OOB); X(MSG_PEEK); X(MSG_DONTROUTE); X(MSG_EOR); X(MSG_TRUNC); X(MSG_CTRUNC); X(MSG_WAITALL);
  X(MSG_DONTWAIT);
  printf("\n#define MCFM_DARWIN_EAI_ERRORS(X)");
  X(EAI_AGAIN); X(EAI_BADFLAGS); X(EAI_FAIL); X(EAI_FAMILY); X(EAI_MEMORY); X(EAI_NONAME);
  X(EAI_SERVICE); X(EAI_SOCKTYPE); X(EAI_SYSTEM); X(EAI_OVERFLOW);
  printf("\n");
}

static void ctype(void) {
  const _RuneLocale *r = &_DefaultRuneLocale;
  printf("// Generated by tools/android/darwin_abi_gen.c: Darwin's C-locale _RuneLocale tables.\n");
  printf("// Do not edit: make darwin-abi.\n");
  const char *names[3] = {"runetype", "maplower", "mapupper"};
  for (int t = 0; t < 3; t++) {
    printf("static const %s kDarwin_%s[%d] = {", t == 0 ? "unsigned int" : "int", names[t], _CACHED_RUNES);
    for (int i = 0; i < _CACHED_RUNES; i++) {
      long long v = t == 0 ? (long long)r->__runetype[i] : t == 1 ? r->__maplower[i] : r->__mapupper[i];
      printf("%s%s0x%llX", i % 8 ? "" : "\n ", i % 8 ? ", " : " ", v);
      if (i % 8 == 7 && i + 1 < _CACHED_RUNES) printf(",");
    }
    printf("\n};\n");
  }
}

int main(int argc, char **argv) {
  if (argc == 2 && !strcmp(argv[1], "header")) header();
  else if (argc == 2 && !strcmp(argv[1], "ctype")) ctype();
  else { fprintf(stderr, "usage: darwin_abi_gen header|ctype\n"); return 2; }
  return 0;
}
