#!/usr/bin/env python3
"""Mach-O tools for the launcher (docs/LAUNCHER.md, Stage 1).

usage: mcfm_image.py imports <macho>              imports as TSV: lib, symbol, fn|data
       mcfm_image.py stubs <imports.tsv> <outdir> [--provided <lib> <symbols>]...
                                                  one C stub source per stubbed library
       mcfm_image.py dylib <executable> <out> [--hooks <hooks.tsv>] [--platform macos|ios]
                           [--host <lib>[,<lib>]...]
                                                  executable -> dylib loadable on macOS (or iOS:
                                                  Stage 4); --host keeps those frameworks real
Exit 2 when the input is unsuitable.
"""
import os
import re
import struct
import subprocess
import sys

# Libraries the image binds to the host system; everything else gets a generated stub.
HOST_LIBS = ("libSystem", "libc++", "libz")

# Names of imports that are data, not functions (constants, ObjC classes, globals). A
# non-lazy import is data only if its name matches or it is bound in ObjC/CFString metadata;
# anything else is a function (a function stub is safe to read, a data stub crashes if called).
DATA_NAME = re.compile(
    r"^_(k[A-Z]\w*|OBJC_\w+|_objc_empty_\w+|__CFConstantStringClassReference"
    r"|NS\w*(Key|Domain|Notification|Mode)|UI\w*(Notification|Key|Invalid|Image)"
    r"|GC\w*Notification|AVAudioSessionCategory\w*|CGRectZero|_NSConcrete\w+)$")


def fail(msg):
    print("mcfm_image.py: " + msg, file=sys.stderr)
    sys.exit(2)


def short_name(install_path):
    """'/usr/lib/libobjc.A.dylib' -> 'libobjc', '.../UIKit.framework/UIKit' -> 'UIKit'."""
    return install_path.rsplit("/", 1)[-1].split(".")[0]


def list_imports(path):
    """{(lib, symbol): kind} from `dyld_info -fixups`."""
    if not os.path.isfile(path):
        fail("no such file: " + path)
    try:
        text = subprocess.run(["dyld_info", "-fixups", path], check=True,
                              capture_output=True, text=True).stdout
    except (OSError, subprocess.CalledProcessError) as e:
        fail("dyld_info failed on %s: %s" % (path, e))
    kinds = {}
    for line in text.splitlines():
        f = line.split()
        if len(f) < 5 or f[3] not in ("bind", "lazy-bind", "weak-bind"):
            continue
        lib, _, sym = f[4].partition("/")
        if not sym:
            continue
        key = (lib, sym)
        lazy = f[3] == "lazy-bind"
        metadata = f[1].startswith("__objc_") or f[1] == "__cfstring"
        data = not lazy and (metadata or DATA_NAME.match(sym) is not None)
        if lazy or kinds.get(key) == "fn":
            kinds[key] = "fn"
        else:
            kinds[key] = "data" if data else "fn"
    return kinds


def linked_libs(path):
    """Short names of every LC_LOAD_DYLIB / LC_LOAD_WEAK_DYLIB, from `otool -L`."""
    text = subprocess.run(["otool", "-L", path], check=True, capture_output=True, text=True).stdout
    return {short_name(line.split()[0]) for line in text.splitlines()[1:] if line.strip()}


def cmd_imports(path):
    rows = {(lib, sym, kind) for (lib, sym), kind in list_imports(path).items()}
    rows |= {(lib, "-", "lib") for lib in linked_libs(path)}
    for row in sorted(rows):
        print("\t".join(row))


MSGSEND = ("_objc_msgSend", "_objc_msgSendSuper2")


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cmd_stubs(tsv, outdir, provided=None):
    by_lib = {}
    try:
        lines = open(tsv).read().splitlines()
    except OSError as e:
        fail("cannot read %s: %s" % (tsv, e))
    for line in lines:
        if not line.strip():
            continue
        try:
            lib, sym, kind = line.split("\t")
        except ValueError:
            fail("bad line in %s: %r" % (tsv, line))
        if kind not in ("fn", "data", "lib"):
            fail("bad kind in %s: %r" % (tsv, line))
        if lib in HOST_LIBS:
            continue
        if provided and sym in provided.get(lib, ()):
            by_lib.setdefault(lib, [])
            continue

        syms = by_lib.setdefault(lib, [])  # a "lib" line alone still yields an (empty) stub
        if kind != "lib":
            syms.append((sym, kind))
    os.makedirs(outdir, exist_ok=True)
    for lib, syms in sorted(by_lib.items()):
        out = ["// Generated by tools/launcher/mcfm_image.py stubs; do not edit.",
               '#include "stub_runtime.h"']
        for n, (sym, kind) in enumerate(sorted(syms)):
            if kind == "data":
                out.append("MCFM_STUB_DATA(%d, %s)" % (n, c_string(sym)))
            elif sym in MSGSEND:
                out.append("MCFM_STUB_MSGSEND(%d, %s, %s)" % (n, c_string(lib), c_string(sym)))
            else:
                out.append("MCFM_STUB_FN(%d, %s, %s)" % (n, c_string(lib), c_string(sym)))
        with open(os.path.join(outdir, lib + ".c"), "w") as fh:
            fh.write("\n".join(out) + "\n")


MH_MAGIC_64, CPU_TYPE_ARM64 = 0xFEEDFACF, 0x0100000C
MH_EXECUTE, MH_DYLIB, MH_PIE = 2, 6, 0x200000
LC_SEGMENT_64, LC_LOAD_DYLIB, LC_ID_DYLIB, LC_LOAD_DYLINKER = 0x19, 0xC, 0xD, 0xE
LC_LOAD_WEAK_DYLIB, LC_MAIN, LC_BUILD_VERSION = 0x80000018, 0x80000028, 0x32
LC_ENCRYPTION_INFO, LC_ENCRYPTION_INFO_64 = 0x21, 0x2C
LC_REEXPORT_DYLIB, LC_LAZY_LOAD_DYLIB, LC_LOAD_UPWARD_DYLIB = 0x8000001F, 0x20, 0x80000023
DYLIB_LOADS = (LC_LOAD_DYLIB, LC_LOAD_WEAK_DYLIB, LC_REEXPORT_DYLIB, LC_LAZY_LOAD_DYLIB, LC_LOAD_UPWARD_DYLIB)
LC_VERSION_MIN = (0x24, 0x25, 0x2F, 0x30)  # macOS, iOS, tvOS, watchOS
PLATFORM_MACOS, MACOS_11 = 1, 0x000B0000
PLATFORM_IOS, IOS_15 = 2, 0x000F0000
PLATFORM_TAGS = {"macos": (PLATFORM_MACOS, MACOS_11), "ios": (PLATFORM_IOS, IOS_15)}
PAD_SIZE = 0x4000
IMAGE_ID = "@rpath/libminecraftpe.dylib"


def read_hooks(path):
    """[(name, unslid address)] from '<name>\\t0x<address>' lines."""
    hooks = []
    try:
        lines = open(path).read().splitlines()
    except OSError as e:
        fail("cannot read %s: %s" % (path, e))
    for line in lines:
        if not line.strip():
            continue
        try:
            name, addr = line.split("\t")
            hooks.append((name, int(addr, 16)))
        except ValueError:
            fail("bad line in %s: %r" % (path, line))
    return hooks


def segment_info(cmds, name):
    """(vmaddr, vmsize, fileoff, [(addr, size)] sections) of an LC_SEGMENT_64, or None."""
    for c in cmds:
        if struct.unpack_from("<I", c)[0] == LC_SEGMENT_64 and segment_name(c) == name:
            vmaddr, vmsize, fileoff = struct.unpack_from("<QQQ", c, 24)
            nsects = struct.unpack_from("<I", c, 64)[0]
            sects = [struct.unpack_from("<QQ", c, 72 + 80 * k + 32) for k in range(nsects)]
            return vmaddr, vmsize, fileoff, sects
    return None


def is_return_or_branch(word):
    """RET Xn, BR Xn or B: the function ends (or leaves) at this instruction."""
    return (word & 0xFFFFFC1F) in (0xD65F0000, 0xD61F0000) or (word & 0xFC000000) == 0x14000000


def check_hooks(data, hooks, tvm, tsize, tfileoff):
    """Every hook needs 12 bytes of its own: aligned, inside __TEXT, not overlapping another hook,
    and not a function that returns or branches away within its first two instructions."""
    by_addr = sorted(hooks, key=lambda h: h[1])
    for (name, addr), nxt in zip(by_addr, by_addr[1:] + [None]):
        if addr % 4:
            fail("hook %s at 0x%x is not 4-byte aligned" % (name, addr))
        if not (tvm <= addr and addr + 12 <= tvm + tsize):
            fail("hook %s at 0x%x is not in __TEXT" % (name, addr))
        if nxt and nxt[1] < addr + 12:
            fail("hooks %s and %s overlap (0x%x, 0x%x)" % (name, nxt[0], addr, nxt[1]))
        first, second = struct.unpack_from("<II", data, addr - tvm + tfileoff)
        if is_return_or_branch(first) or is_return_or_branch(second):
            fail("hook %s at 0x%x: function is shorter than 12 bytes" % (name, addr))


def patch_hooks(data, cmds, hooks):
    """Replace each hooked function's first 12 bytes with adrp x16 / ldr x16 / br x16 through
    the hook table (end of __DATA; same rule as shared/apple/hook_table.cpp)."""
    text, data_seg = segment_info(cmds, "__TEXT"), segment_info(cmds, "__DATA")
    if not text or not data_seg:
        fail("no __TEXT or __DATA segment")
    dvm, dsize, _, dsects = data_seg
    table = (max([dvm] + [a + s for a, s in dsects]) + 15) & ~15
    if len(hooks) > (dvm + dsize - table) // 8:
        fail("hook table full: %d hooks, room for %d" % (len(hooks), (dvm + dsize - table) // 8))
    tvm, tsize, tfileoff, _ = text
    check_hooks(data, hooks, tvm, tsize, tfileoff)
    for i, (name, addr) in enumerate(hooks):
        slot = table + 8 * i
        pages = (slot >> 12) - (addr >> 12)
        adrp = 0x90000000 | ((pages & 3) << 29) | (((pages >> 2) & 0x7FFFF) << 5) | 16
        ldr = 0xF9400000 | (((slot & 0xFFF) // 8) << 10) | (16 << 5) | 16
        br = 0xD61F0200
        struct.pack_into("<III", data, addr - tvm + tfileoff, adrp, ldr, br)


def dylib_command(cmd, name):
    raw = name.encode() + b"\0"
    size = (24 + len(raw) + 7) & ~7
    return struct.pack("<IIIIII", cmd, size, 24, 2, 0x10000, 0x10000) + raw.ljust(size - 24, b"\0")


def segment_name(cmd_bytes):
    return cmd_bytes[8:24].rstrip(b"\0").decode()


def cmd_dylib(src, dst, hooks=(), platform="macos", host_libs=()):
    if platform not in PLATFORM_TAGS:
        fail("unknown platform %s (macos or ios)" % platform)
    tag_platform, tag_version = PLATFORM_TAGS[platform]
    keep = set(HOST_LIBS) | set(host_libs)
    try:
        data = bytearray(open(src, "rb").read())
    except OSError as e:
        fail("cannot read %s: %s" % (src, e))
    if len(data) < 32:
        fail("not a thin arm64 Mach-O: " + src)
    magic, cpu, sub, ftype, ncmds, sizeofcmds, flags, res = struct.unpack_from("<IiiIIIII", data, 0)
    if magic != MH_MAGIC_64 or cpu != CPU_TYPE_ARM64:
        fail("not a thin arm64 Mach-O (lipo -thin arm64 first): " + src)
    if ftype != MH_EXECUTE:
        fail("not an executable (already converted?): " + src)

    end = 32 + sizeofcmds
    if end > len(data):
        fail("malformed load commands (sizeofcmds past the end of the file): " + src)
    cmds, off = [], 32
    for _ in range(ncmds):
        if off + 8 > end:
            fail("malformed load commands (more commands than sizeofcmds holds): " + src)
        cmd, size = struct.unpack_from("<II", data, off)
        if size < 8 or off + size > end:
            fail("malformed load commands (bad cmdsize %d at offset %d): %s" % (size, off, src))
        if cmd == LC_SEGMENT_64 and (size < 72 or 72 + 80 * struct.unpack_from("<I", data, off + 64)[0] > size):
            fail("malformed load commands (segment sections past cmdsize): " + src)
        cmds.append(bytes(data[off:off + size]))
        off += size
    text = segment_info(cmds, "__TEXT")
    if not text:
        fail("no __TEXT segment: " + src)
    text_vmaddr = text[0]

    first_data, out = len(data), [dylib_command(LC_ID_DYLIB, IMAGE_ID)]
    tagged = False
    for c in cmds:
        cmd = struct.unpack_from("<I", c)[0]
        if cmd in (LC_ENCRYPTION_INFO, LC_ENCRYPTION_INFO_64) and len(c) >= 20 and struct.unpack_from("<I", c, 16)[0]:
            fail("encrypted (cryptid %d): decrypt the game first: %s" % (struct.unpack_from("<I", c, 16)[0], src))
        if cmd in (LC_MAIN, LC_LOAD_DYLINKER, LC_ENCRYPTION_INFO, LC_ENCRYPTION_INFO_64):
            continue
        if cmd in LC_VERSION_MIN or cmd == LC_BUILD_VERSION:
            if not tagged:  # one platform tag, however many platform commands the input has
                out.append(struct.pack("<IIIIII", LC_BUILD_VERSION, 24, tag_platform, tag_version, tag_version, 0))
                tagged = True
            continue
        if cmd in DYLIB_LOADS:
            name_off = struct.unpack_from("<I", c, 8)[0]
            name = c[name_off:].split(b"\0")[0].decode()
            lib = short_name(name)
            out.append(c if lib in keep else dylib_command(cmd, "@rpath/mcfm_stub_%s.dylib" % lib))
            continue
        if cmd == LC_SEGMENT_64:
            c = bytearray(c)
            if segment_name(c) == "__PAGEZERO":
                # Keep the slot: fixup opcodes address segments by index.
                c[8:24] = b"__MCFM_PAD".ljust(16, b"\0")
                struct.pack_into("<QQ", c, 24, text_vmaddr - PAD_SIZE, PAD_SIZE)
            nsects = struct.unpack_from("<I", c, 64)[0]
            for k in range(nsects):
                s = 72 + 80 * k
                if c[s:s + 7] == b"__objc_":  # hide ObjC metadata from the system libobjc
                    c[s + 2:s + 3] = b"x"
                sect_off, sect_size = struct.unpack_from("<I", c, s + 48)[0], struct.unpack_from("<Q", c, s + 40)[0]
                if sect_off and sect_size:
                    first_data = min(first_data, sect_off)
            c = bytes(c)
        out.append(c)

    blob = b"".join(out)
    if 32 + len(blob) > first_data:
        fail("not enough header padding (%d bytes of load commands, %d available): %s"
             % (len(blob), first_data - 32, src))
    if hooks:
        patch_hooks(data, cmds, hooks)
    data[32:32 + max(sizeofcmds, len(blob))] = b"\0" * max(sizeofcmds, len(blob))
    data[32:32 + len(blob)] = blob
    struct.pack_into("<IiiIIIII", data, 0, magic, cpu, sub, MH_DYLIB, len(out), len(blob), flags & ~MH_PIE, res)
    with open(dst, "wb") as fh:
        fh.write(data)


def main(argv):
    if len(argv) == 3 and argv[1] == "imports":
        return cmd_imports(argv[2])
    if len(argv) >= 4 and argv[1] == "stubs" and (len(argv) - 4) % 3 == 0:
        provided = {}
        for k in range(4, len(argv), 3):
            if argv[k] != "--provided":
                fail(__doc__.strip())
            try:
                provided[argv[k + 1]] = set(open(argv[k + 2]).read().split())
            except OSError as e:
                fail("cannot read %s: %s" % (argv[k + 2], e))
        return cmd_stubs(argv[2], argv[3], provided)
    if len(argv) >= 4 and len(argv) % 2 == 0 and argv[1] == "dylib":
        hooks, platform, host_libs = (), "macos", ()
        for k in range(4, len(argv), 2):
            if argv[k] == "--hooks":
                hooks = read_hooks(argv[k + 1])
            elif argv[k] == "--platform":
                platform = argv[k + 1]
            elif argv[k] == "--host":
                host_libs = tuple(x for x in argv[k + 1].split(",") if x)
            else:
                fail(__doc__.strip())
        return cmd_dylib(argv[2], argv[3], hooks, platform, host_libs)
    fail(__doc__.strip())


if __name__ == "__main__":
    try:
        main(sys.argv)
    except struct.error as e:  # truncated or inconsistent Mach-O the checks above did not name
        fail("malformed Mach-O: %s" % e)
