#!/usr/bin/env python3
"""gen_runtime_symbols.py <sorted symbol names> <the same names demangled, line by line>: a C++
file with mcfm_runtime_symbol(name), the address of each of the runtime's own C++ symbols
(libc++, libc++abi, libunwind), found by binary search. Each name is referenced through an asm
label, so the symbols stay hidden in the launcher library (docs/research/android-launcher.md).

Constructors and (non-deleting) destructors are handed out through thunks that return `this`:
Apple's arm64 C++ ABI returns `this` from them and the game's code uses it; Android's (generic
AArch64) does not, and clang offers the Apple ABI only for Darwin targets."""
import re
import sys


def split_top(qualified):
    """Splits A::B<x::y>::C at '::' outside template arguments."""
    parts, depth, cur, i = [], 0, '', 0
    while i < len(qualified):
        ch = qualified[i]
        if ch in '<(':
            depth += 1
        elif ch in '>)':
            depth -= 1
        if depth == 0 and qualified.startswith('::', i):
            parts.append(cur)
            cur = ''
            i += 2
            continue
        cur += ch
        i += 1
    parts.append(cur)
    return parts


def base_name(component):
    return component.split('<', 1)[0].split('[abi:', 1)[0]


def is_this_returning(mangled, demangled):
    """A complete/base constructor or a complete/base destructor (C1, C2, D1, D2)."""
    if not mangled.startswith('_ZN'):
        return False
    paren = demangled.find('(')
    if paren <= 0:
        return False
    parts = split_top(demangled[:paren])
    if len(parts) < 2:
        return False
    cls, fn = base_name(parts[-2]), base_name(parts[-1])
    if fn != cls and fn != '~' + cls:
        return False
    # The structor kind from the mangling: C1/C2 constructors, D1/D2 destructors return this;
    # D0 (deleting) returns nothing.
    kinds = re.findall(r'(C[123]|D[012])(?:B\d+\w+?)*E', mangled)
    return bool(kinds) and kinds[-1] in ('C1', 'C2', 'D1', 'D2')


pairs = [(n.strip(), d.rstrip('\n')) for n, d in zip(open(sys.argv[1]), open(sys.argv[2])) if n.strip()]
names = [n for n, _ in pairs]
demangled = [d for _, d in pairs]
thunked = {n for n, d in zip(names, demangled) if is_this_returning(n, d)}

# Self-checks, so a different LLVM fails here instead of building wrong thunks: a thunk keeps
# `this` in a 32-byte frame, so it must not see variadic or stack-passed arguments.
for n, d in zip(names, demangled):
    if n in thunked:
        params = d[d.find('(') + 1:d.rfind(')')]
        depth, count = 0, (1 if params.strip() else 0)
        for ch in params:
            if ch in '<(':
                depth += 1
            elif ch in '>)':
                depth -= 1
            elif ch == ',' and depth == 0:
                count += 1
        if '...' in params:
            sys.exit(f'gen_runtime_symbols: variadic structor {n}: a thunk cannot forward its stack arguments')
        if count + 1 > 8:
            sys.exit(f'gen_runtime_symbols: {n} has stack arguments: the thunk frame would shift them')
        if not any(t in n for t in ('C1E', 'C2E', 'D1E', 'D2E', 'C1B', 'C2B', 'D1B', 'D2B')):
            sys.exit(f'gen_runtime_symbols: {n} is thunked but its mangled name has no C1/C2/D1/D2')

print("// Generated by android/launcher/runtime/gen_runtime_symbols.py from the runtime's objects.")
print("#include <stdlib.h>\n#include <string.h>\n")
print('extern "C" {')
for i, n in enumerate(names):
    print(f'extern char mcfm_rt_{i} __asm__("{n}");')
    if n in thunked:
        print(f'extern char mcfm_this_{i} __asm__("mcfm_this_{i}");')
print('}\n')
# Each thunk: keep `this` (x0) across the call, return it. A frame record and CFI, so exceptions
# thrown by the constructor unwind through it.
print('__asm__(".text\\n.p2align 2\\n"')
for i, n in enumerate(names):
    if n not in thunked:
        continue
    print(f'    ".type mcfm_this_{i},%function\\nmcfm_this_{i}:\\n.cfi_startproc\\n"')
    print('    "stp x29, x30, [sp, #-32]!\\n.cfi_def_cfa_offset 32\\n.cfi_offset x30, -24\\n.cfi_offset x29, -32\\n"')
    print(f'    "mov x29, sp\\nstr x0, [sp, #16]\\nbl {n}\\nldr x0, [sp, #16]\\nldp x29, x30, [sp], #32\\nret\\n"')
    print(f'    ".cfi_endproc\\n.size mcfm_this_{i}, .-mcfm_this_{i}\\n"')
print(');\n')
print("namespace {\nstruct Entry { const char *name; const void *address; };\nconst Entry kRuntime[] = {")
for i, n in enumerate(names):
    target = f'mcfm_this_{i}' if n in thunked else f'mcfm_rt_{i}'
    print(f'    {{"{n}", &{target}}},')
print(f"""}};
int compare(const void *key, const void *entry) {{
  return strcmp(static_cast<const char *>(key), static_cast<const Entry *>(entry)->name);
}}
}}  // namespace

// The runtime's definition of `name` (a C++ symbol name as the linker sees it), or null.
// Constructors and destructors: a thunk returning `this` ({len(thunked)} of them).
extern "C" void *mcfm_runtime_symbol(const char *name) {{
  const Entry *e = static_cast<const Entry *>(bsearch(name, kRuntime, sizeof kRuntime / sizeof kRuntime[0], sizeof kRuntime[0], compare));
  return e ? const_cast<void *>(e->address) : nullptr;
}}

extern "C" size_t mcfm_runtime_symbol_count(void) {{ return sizeof kRuntime / sizeof kRuntime[0]; }}""")
