#!/usr/bin/env python3
"""gen_runtime_symbols.py <sorted symbol names>: a C++ file with mcfm_runtime_symbol(name), the
address of each of the runtime's own C++ symbols (libc++, libc++abi, libunwind), found by binary
search. Each name is referenced through an asm label, so the symbols can stay hidden in the
launcher library (docs/research/android-launcher.md, "One C++ runtime per process")."""
import sys

names = [n.strip() for n in open(sys.argv[1]) if n.strip()]
print("// Generated by android/launcher/runtime/gen_runtime_symbols.py from the runtime's objects.")
print("#include <stdlib.h>\n#include <string.h>\n")
print('extern "C" {')
for i, n in enumerate(names):
    print(f'extern char mcfm_rt_{i} __asm__("{n}");')
print("}\n\nnamespace {\nstruct Entry { const char *name; const void *address; };\nconst Entry kRuntime[] = {")
for i, n in enumerate(names):
    print(f'    {{"{n}", &mcfm_rt_{i}}},')
print("""};
int compare(const void *key, const void *entry) {
  return strcmp(static_cast<const char *>(key), static_cast<const Entry *>(entry)->name);
}
}  // namespace

// The runtime's definition of `name` (a C++ symbol name as the linker sees it), or null.
extern "C" void *mcfm_runtime_symbol(const char *name) {
  const Entry *e = static_cast<const Entry *>(bsearch(name, kRuntime, sizeof kRuntime / sizeof kRuntime[0], sizeof kRuntime[0], compare));
  return e ? const_cast<void *>(e->address) : nullptr;
}

extern "C" size_t mcfm_runtime_symbol_count(void) { return sizeof kRuntime / sizeof kRuntime[0]; }""")
