#!/bin/bash
# Rebuild the Catalyst-converted app from the untouched original.
# usage: convert.sh <orig.app> <out.app> [libmcpekbm.dylib]
set -euo pipefail
SRC="$1"; DST="$2"; DYLIB="${3:-}"
MARK=".mcpekbm-generated"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
if [ -n "$DYLIB" ]; then
  [ -f "$DYLIB" ] || { echo "convert.sh: dylib $DYLIB not found"; exit 1; }
  DYLIB="$(cd "$(dirname "$DYLIB")" && pwd)/$(basename "$DYLIB")"
fi

# Physical path of $1, even when it (or some of its parents) does not exist yet.
phys() {
  local p="$1" rest=""
  while [ ! -d "$p" ]; do rest="/$(basename "$p")$rest"; p="$(dirname "$p")"; done
  echo "$(cd "$p" && pwd -P)$rest"
}
die() { echo "convert.sh: $*"; exit 1; }

[ -x "$SRC/minecraftpe2" ] || die "$SRC is not the original app"
case "$DST" in *.app) ;; *) die "output must be a .app path: $DST" ;; esac
SRC_P="$(phys "$SRC")"; DST_P="$(phys "$DST")"
case "$DST_P/" in "$SRC_P/"*) die "output is inside the original: $DST" ;; esac
case "$SRC_P/" in "$DST_P/"*) die "output contains the original: $DST" ;; esac
if [ -e "$DST" ] && [ ! -e "$DST/$MARK" ]; then
  die "$DST exists and was not generated by convert.sh; not touching it"
fi

pgrep -x minecraftpe2 >/dev/null && die "Minecraft is running; quit it first so no progress is lost"
rm -rf "$DST"
mkdir -p "$(dirname "$DST")"
cp -R "$SRC" "$DST"
touch "$DST/$MARK"
cd "$DST"
rm -rf _CodeSignature
find Frameworks -name _CodeSignature -prune -exec rm -rf {} +

for f in minecraftpe2 Frameworks/*.dylib Frameworks/XSAPITCUI.framework/XSAPITCUI; do
  lipo "$f" -thin arm64 -output "$f.thin" && mv "$f.thin" "$f"
  vtool -set-build-version maccatalyst 11.0 14.0 -replace -output "$f.v" "$f" 2>/dev/null && mv "$f.v" "$f"
done

/usr/libexec/PlistBuddy -c 'Delete :UIRequiresFullScreen' Info.plist 2>/dev/null || true

if [ -n "$DYLIB" ]; then
  cp "$DYLIB" Frameworks/libmcpekbm.dylib
  python3 -I "$ROOT/tools/inject.py" minecraftpe2 @executable_path/Frameworks/libmcpekbm.dylib
fi

xattr -rc .
for f in Frameworks/*.dylib Frameworks/XSAPITCUI.framework; do codesign -f -s - "$f" 2>/dev/null; done
codesign -f -s - "$DST"
codesign -v "$DST"
echo "convert.sh: built $DST"
