#!/bin/bash
# Rebuild the Catalyst-converted app from the untouched original.
# usage: convert.sh <orig.app> <out.app> [libmcpekbm.dylib]
set -euo pipefail
SRC="$1"; DST="$2"; DYLIB="${3:-}"
MARK=".mcpekbm-generated"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
if [ -n "$DYLIB" ]; then
  [ -f "$DYLIB" ] || { echo "convert.sh: dylib $DYLIB not found"; exit 1; }
  DYLIB="$(cd "$(dirname "$DYLIB")" && pwd)/$(basename "$DYLIB")"
fi

[ -x "$SRC/minecraftpe2" ] || { echo "convert.sh: $SRC is not the original app"; exit 1; }
[ "$(cd "$SRC" && pwd)" != "$(mkdir -p "$DST" && cd "$DST" && pwd)" ] || { echo "convert.sh: refusing to overwrite the original"; exit 1; }
if [ -e "$DST/minecraftpe2" ] && [ ! -e "$DST/$MARK" ]; then
  echo "convert.sh: $DST exists and was not generated by convert.sh; not touching it"; exit 1
fi

pkill -x minecraftpe2 2>/dev/null || true
rm -rf "$DST"
mkdir -p "$(dirname "$DST")"
cp -R "$SRC" "$DST"
touch "$DST/$MARK"
cd "$DST"
rm -rf _CodeSignature
find Frameworks -name _CodeSignature -prune -exec rm -rf {} +

for f in minecraftpe2 Frameworks/*.dylib Frameworks/XSAPITCUI.framework/XSAPITCUI; do
  lipo "$f" -thin arm64 -output "$f.thin" && mv "$f.thin" "$f"
  vtool -set-build-version maccatalyst 11.0 14.0 -replace -output "$f.v" "$f" 2>/dev/null && mv "$f.v" "$f"
done

/usr/libexec/PlistBuddy -c 'Delete :UIRequiresFullScreen' Info.plist 2>/dev/null || true

if [ -n "$DYLIB" ]; then
  cp "$DYLIB" Frameworks/libmcpekbm.dylib
  python3 -I "$ROOT/tools/inject.py" minecraftpe2 @executable_path/Frameworks/libmcpekbm.dylib
fi

xattr -rc .
for f in Frameworks/*.dylib Frameworks/XSAPITCUI.framework; do codesign -f -s - "$f" 2>/dev/null; done
codesign -f -s - "$DST"
codesign -v "$DST"
echo "convert.sh: built $DST"
